title:               "Unhandled Exception"
description:        "everyday a developer wakes up and starts coding"


author:
  name: nezumi
  #email: 
  github: nezumi-quasar
  twitter: emagar83
  #pinterest: asd123
  linkedin: emanuele-garofalo-ba12ab31
  #bio: Your stylish, minimalist theme!
  email_md5: 082fcf499b13603f2d604b0afaf7f89d

gravatar_hash:      "082fcf499b13603f2d604b0afaf7f89d"
linkedin_url:       "https://bit.ly/2e8dXx8"
disqus:   ""
#google_analytics:   not configured
background:         "/assets/imgs/deserve_bg.jpg"
resources:          "resources"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

url: "https://blog.unhandledexception.it"
BASE_PATH: https://blog.unhandledexception.it

paginate:           10
paginate_path:      "/page:num/"

highlighter:        rouge
markdown:           kramdown

nav:
  - name:           "Slideshares"
    href:           "/pages/slideshares"
  - name:           "Bio"
    href:           "/pages/bio"
  - name:           "Publications"
    href:           "/pages/publications"

sass:
  sass_dir: resources/css
  style:    expanded

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-paginate
